/* The standing collection — 33 observations, hand-reviewed frame by frame.
   Each entry is a small looping mp4 served from the Tenor/Giphy CDNs; nothing is
   stored in this repo. A clip that ever goes dark is skipped at runtime by
   app.js and the next dog steps forward, so the button never fails. */
const DECK = [
  { id: "cHcMjOauJP0TbKQIfY",      src: "https://media.giphy.com/media/cHcMjOauJP0TbKQIfY/giphy.mp4",                            poster: "https://media.giphy.com/media/cHcMjOauJP0TbKQIfY/200w.gif" },
  { id: "Ky-om77Hplw",             src: "https://media.tenor.com/Ky-om77HplwAAAPs/dog-spinning-in-circles.mp4",                  poster: "https://media.tenor.com/Ky-om77HplwAAAAM/dog-spinning-in-circles.gif" },
  { id: "SUX4IOUfjP2JbUOnWF",      src: "https://media.giphy.com/media/SUX4IOUfjP2JbUOnWF/giphy.mp4",                            poster: "https://media.giphy.com/media/SUX4IOUfjP2JbUOnWF/200w.gif" },
  { id: "0DSUBdA_aUk",             src: "https://media.tenor.com/0DSUBdA_aUkAAAPs/dog-tail-circles.mp4",                         poster: "https://media.tenor.com/0DSUBdA_aUkAAAAM/dog-tail-circles.gif" },
  { id: "1JuiBtVYgBQ",             src: "https://media.tenor.com/1JuiBtVYgBQAAAPs/dog-running-dog-sprinting.mp4",                poster: "https://media.tenor.com/1JuiBtVYgBQAAAAM/dog-running-dog-sprinting.gif" },
  { id: "-IZNU2EY-Bk",             src: "https://media.tenor.com/-IZNU2EY-BkAAAPs/dog-zoomies.mp4",                              poster: "https://media.tenor.com/-IZNU2EY-BkAAAAM/dog-zoomies.gif" },
  { id: "ZSNS279zbRM",             src: "https://media.tenor.com/ZSNS279zbRMAAAPs/zoom-zoomies.mp4",                             poster: "https://media.tenor.com/ZSNS279zbRMAAAAM/zoom-zoomies.gif" },
  { id: "OnEiwfys7B0",             src: "https://media.tenor.com/OnEiwfys7B0AAAPs/dog-running.mp4",                              poster: "https://media.tenor.com/OnEiwfys7B0AAAAM/dog-running.gif" },
  { id: "U7OEfslc3oA",             src: "https://media.tenor.com/U7OEfslc3oAAAAPs/dog.mp4",                                      poster: "https://media.tenor.com/U7OEfslc3oAAAAAM/dog.gif" },
  { id: "UCRus1hBN7o",             src: "https://media.tenor.com/UCRus1hBN7oAAAPs/zoomies-running-in-circles.mp4",               poster: "https://media.tenor.com/UCRus1hBN7oAAAAM/zoomies-running-in-circles.gif" },
  { id: "f3Btth52FP8",             src: "https://media.tenor.com/f3Btth52FP8AAAPs/dog-doggy.mp4",                                poster: "https://media.tenor.com/f3Btth52FP8AAAAM/dog-doggy.gif" },
  { id: "Zr4JyvsXZXg",             src: "https://media.tenor.com/Zr4JyvsXZXgAAAPs/dog-running-dog-run.mp4",                      poster: "https://media.tenor.com/Zr4JyvsXZXgAAAAM/dog-running-dog-run.gif" },
  { id: "Fd3bYRzF9cg",             src: "https://media.tenor.com/Fd3bYRzF9cgAAAPs/dog-dog-jumping-at-camera.mp4",                poster: "https://media.tenor.com/Fd3bYRzF9cgAAAAM/dog-dog-jumping-at-camera.gif" },
  { id: "fWTGwxAuS-k",             src: "https://media.tenor.com/fWTGwxAuS-kAAAPs/n.mp4",                                        poster: "https://media.tenor.com/fWTGwxAuS-kAAAAM/n.gif" },
  { id: "O_NkF_T5Knk",             src: "https://media.tenor.com/O_NkF_T5KnkAAAPs/dogs-chasing.mp4",                             poster: "https://media.tenor.com/O_NkF_T5KnkAAAAM/dogs-chasing.gif" },
  { id: "zSfx2DsTbmI",             src: "https://media.tenor.com/zSfx2DsTbmIAAAPs/border-collie-dog.mp4",                        poster: "https://media.tenor.com/zSfx2DsTbmIAAAAM/border-collie-dog.gif" },
  { id: "4jSFH4ktsHs",             src: "https://media.tenor.com/4jSFH4ktsHsAAAPs/dog-spin-spinning-dog.mp4",                    poster: "https://media.tenor.com/4jSFH4ktsHsAAAAM/dog-spin-spinning-dog.gif" },
  { id: "McnKvE9fRgc",             src: "https://media.tenor.com/McnKvE9fRgcAAAPs/popi-wee.mp4",                                 poster: "https://media.tenor.com/McnKvE9fRgcAAAAM/popi-wee.gif" },
  { id: "7zN_9AtvkJM",             src: "https://media.tenor.com/7zN_9AtvkJMAAAPs/shake-it-off-yorkie.mp4",                      poster: "https://media.tenor.com/7zN_9AtvkJMAAAAM/shake-it-off-yorkie.gif" },
  { id: "s0jsKwzC3Pc",             src: "https://media.tenor.com/s0jsKwzC3PcAAAPs/squirmy-dog.mp4",                              poster: "https://media.tenor.com/s0jsKwzC3PcAAAAM/squirmy-dog.gif" },
  { id: "xSffkhRiWLM",             src: "https://media.tenor.com/xSffkhRiWLMAAAPs/jevanna-biodegradable-grass-and-seed-mat.mp4", poster: "https://media.tenor.com/xSffkhRiWLMAAAAM/jevanna-biodegradable-grass-and-seed-mat.gif" },
  { id: "4VBfx98lgGo",             src: "https://media.tenor.com/4VBfx98lgGoAAAPs/sledding-viralhog.mp4",                        poster: "https://media.tenor.com/4VBfx98lgGoAAAAM/sledding-viralhog.gif" },
  { id: "yyXtKw3dMOA",             src: "https://media.tenor.com/yyXtKw3dMOAAAAPs/dog-snow.mp4",                                 poster: "https://media.tenor.com/yyXtKw3dMOAAAAAM/dog-snow.gif" },
  { id: "cLO1115QsLM",             src: "https://media.tenor.com/cLO1115QsLMAAAPs/playful-snow.mp4",                             poster: "https://media.tenor.com/cLO1115QsLMAAAAM/playful-snow.gif" },
  { id: "7jMVLVdHBeY",             src: "https://media.tenor.com/7jMVLVdHBeYAAAPs/playing-the-pet-collective.mp4",               poster: "https://media.tenor.com/7jMVLVdHBeYAAAAM/playing-the-pet-collective.gif" },
  { id: "DZI2REpjGoE",             src: "https://media.tenor.com/DZI2REpjGoEAAAPs/dog-run.mp4",                                  poster: "https://media.tenor.com/DZI2REpjGoEAAAAM/dog-run.gif" },
  { id: "54_0Km4-How",             src: "https://media.tenor.com/54_0Km4-HowAAAPs/jump-water.mp4",                               poster: "https://media.tenor.com/54_0Km4-HowAAAAM/jump-water.gif" },
  { id: "zehJjvklkDo",             src: "https://media.tenor.com/zehJjvklkDoAAAPs/golden-retriever-walkies.mp4",                 poster: "https://media.tenor.com/zehJjvklkDoAAAAM/golden-retriever-walkies.gif" },
  { id: "M7Z9ElvDpQ4",             src: "https://media.tenor.com/M7Z9ElvDpQ4AAAPs/labrador-retriever-labrador.mp4",              poster: "https://media.tenor.com/M7Z9ElvDpQ4AAAAM/labrador-retriever-labrador.gif" },
  { id: "5cGFX2Ropkc",             src: "https://media.tenor.com/5cGFX2RopkcAAAPs/diesel-golden-retriever.mp4",                  poster: "https://media.tenor.com/5cGFX2RopkcAAAAM/diesel-golden-retriever.gif" },
  { id: "2CjWuNecvIs",             src: "https://media.tenor.com/2CjWuNecvIsAAAPs/moon-husky.mp4",                               poster: "https://media.tenor.com/2CjWuNecvIsAAAAM/moon-husky.gif" },
  { id: "DzQjcYDZim8",             src: "https://media.tenor.com/DzQjcYDZim8AAAPs/dog-fun.mp4",                                  poster: "https://media.tenor.com/DzQjcYDZim8AAAAM/dog-fun.gif" },
  { id: "MGMEZeJv_2o",             src: "https://media.tenor.com/MGMEZeJv_2oAAAPs/running-around-the-trickstars.mp4",            poster: "https://media.tenor.com/MGMEZeJv_2oAAAAM/running-around-the-trickstars.gif" },
];
